# Generated by Django 5.1.2 on 2024-10-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_schedule',
            old_name='applyer',
            new_name='company',
        ),
        migrations.AddField(
            model_name='company_schedule',
            name='jobrole',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='company_schedule',
            name='status',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='company_schedule',
            name='username',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
