# Generated by Django 5.1.2 on 2024-10-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_dob_userapply_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapply',
            name='date',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='userapply',
            name='place',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='userapply',
            name='time',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
